version: "3.8"

services:
  app:
    build:
      dockerfile: Dockerfile-app
      context: ./
    restart: unless-stopped
    depends_on:
      - mail
      - db
    environment:
      NODE_ENV: production
      NODE_CONFIG_ENV: docker
    ports:
      - 80:80

  mail:
    build:
      dockerfile: Dockerfile-mail
      context: ./
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: production
      NODE_CONFIG_ENV: docker
    ports:
      - 25:25

  db:
    build:
      dockerfile: Dockerfile-db
      context: ./
    restart: unless-stopped
    volumes:
      - ./db:/data
    ports:
      - 8080:8080
      - 28015:28015
